### ISSUE TITLE
FXtrayIcon error when used it with springboot fx application

### ISSUE THREAD

**Issue by DEV-A7med** [dustinkredmond/FXTrayIcon#24]
When I'm using FXTrayIcon with JavaFX application that's work fine but now I need to run my project as spring-boot fx project 
I follow instructions here to run the spring-boot project as FX project
[https://blog.jetbrains.com/idea/2019/11/tutorial-reactive-spring-boot-a-javafx-spring-boot-application/](url)

but when I used FXTrayIcon get me this exception message
```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.awt.HeadlessException
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:165)
	at java.desktop/java.awt.MenuComponent.<init>(MenuComponent.java:181)
	at java.desktop/java.awt.MenuItem.<init>(MenuItem.java:224)
	at java.desktop/java.awt.MenuItem.<init>(MenuItem.java:208)
	at java.desktop/java.awt.Menu.<init>(Menu.java:163)
	at java.desktop/java.awt.Menu.<init>(Menu.java:144)
	at java.desktop/java.awt.PopupMenu.<init>(PopupMenu.java:88)
	at java.desktop/java.awt.PopupMenu.<init>(PopupMenu.java:75)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.<init>(FXTrayIcon.java:885)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.<init>(FXTrayIcon.java:84)
	at com.dustinredmond.fxtrayicon.FXTrayIcon$Builder.<init>(FXTrayIcon.java:153)
	at com.ahmedsr.alphasyncui.AlphaSyncApplication.start(AlphaSyncApplication.java:29)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	... 1 more
```

I ask about what's capabilities to integrate fxtrayicon with spring-boot-fx

**Comment by EasyG0ing1** [comment]
Springboot... I looked at that once ... then I didn't ... I've been perhaps putting off the inevitable.
