### ISSUE TITLE
NullPointerException when null MenuItem()

### ISSUE THREAD

**Issue by ctoabidmaqbool** [dustinkredmond/FXTrayIcon#61]
I have used codding somethings like this:

```
MenuItem mnuBuizName = new MenuItem();
trayIcon.addMenuItem(mnuBuizName);
```

Error:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.awt.MenuItem.getLabel()" is null
	at com.dustinredmond.fxtrayicon.FXTrayIcon.isNotUnique(FXTrayIcon.java:1434)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.addMenuItemPrivately(FXTrayIcon.java:989)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.lambda$addMenuItem$9(FXTrayIcon.java:966)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.awt.MenuItem.getLabel()" is null
	at com.dustinredmond.fxtrayicon.FXTrayIcon.isNotUnique(FXTrayIcon.java:1434)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.addMenuItemPrivately(FXTrayIcon.java:989)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.lambda$addMenuItem$9(FXTrayIcon.java:966)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.awt.MenuItem.getLabel()" is null
	at com.dustinredmond.fxtrayicon.FXTrayIcon.isNotUnique(FXTrayIcon.java:1434)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.addMenuItemPrivately(FXTrayIcon.java:989)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.lambda$addMenuItem$9(FXTrayIcon.java:966)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.awt.MenuItem.getLabel()" is null
	at com.dustinredmond.fxtrayicon.FXTrayIcon.isNotUnique(FXTrayIcon.java:1434)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.addMenuItemPrivately(FXTrayIcon.java:989)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.lambda$addMenuItem$9(FXTrayIcon.java:966)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.awt.MenuItem.getLabel()" is null
	at com.dustinredmond.fxtrayicon.FXTrayIcon.isNotUnique(FXTrayIcon.java:1434)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.addMenuItemPrivately(FXTrayIcon.java:989)
	at com.dustinredmond.fxtrayicon.FXTrayIcon.lambda$addMenuItem$9(FXTrayIcon.java:966)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by dustinkredmond** [comment]
It looks like the AWT API is requiring you to have set a label on the MenuItem before it is added to the TrayIcon. Please try setting a label on the MenuItem first before adding it to the TrayIcon.

**Comment by ctoabidmaqbool** [comment]
@dustinkredmond Hum! I have already tried it, If MenuItem is assigned as empty string, then all works good. e.g. 

```
MenuItem mnuBuizName = new MenuItem("");
```

But I think, it should also except empty parameter / null values because in AWT/SWING it's excepting it!

**Comment by dustinkredmond** [comment]
I've changed the `AWTUtils` class with commit 1d11f3d to check if the text passed in the FX `MenuItem` is null, if so, we'll call the AWT constructor with an empty `String`. This should take care of your issue going forward.
