### ISSUE TITLE
addMenuItem after tray is shown throws exception

### ISSUE THREAD

**Issue by mrgreywater** [dustinkredmond/FXTrayIcon#71]
```java
var tray = new MyFXTrayIcon(primaryStage, ...);
tray.show();
tray.addMenuItem(new MenuItem("Item"));
```

throws 

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: index less than zero.
	at java.desktop/java.awt.Menu.insert(Menu.java:323)
	at com.dustinredmond.fxtrayicon@4.0.1/com.dustinredmond.fxtrayicon.FXTrayIcon.addMenuItemPrivately(FXTrayIcon.java:998)
	at com.dustinredmond.fxtrayicon@4.0.1/com.dustinredmond.fxtrayicon.FXTrayIcon.lambda$addMenuItem$9(FXTrayIcon.java:970)
```

**Comment by dustinkredmond** [comment]
Should be an easy enough fix, let me check on this one.

**Comment by EasyG0ing1** [comment]
@mrgreywater I tried the exact same code that you posted and I don't get the error. Are you using version 4.0.1 of the library?

**Comment by mrgreywater** [comment]
@EasyG0ing1 The problem is this line here:
https://github.com/dustinkredmond/FXTrayIcon/blob/a3fc68bec00cccb87ffde278d4b866bc630991e3/src/main/java/com/dustinredmond/fxtrayicon/FXTrayIcon.java#L999

if addExitMenuItem is true, the menu is shown but no items in the popupMenu exist, then this.popupMenu.getItemCount() - 1 is negative, when it should be zero.

**Comment by EasyG0ing1** [comment]
@mrgreywater 

I updated two methods that had the same code in it and pushed it into my existing pull request. The new methods will have this in them now:
```Java
if (addExitMenuItem && shown) {
	int index = this.popupMenu.getItemCount() - 1;
	index = (index < 0) ? 0 : index;
	this.popupMenu.insert(AWTUtils.convertFromJavaFX(menuItem), index);
}
```

**Comment by EasyG0ing1** [comment]
@mrgreywater Scratch that, I changed the code to this since this makes much more sense in terms which index to use when adding an item to an list or an array:

```Java
if(addExitMenuItem && shown) {
	int index = this.popupMenu.getItemCount();
	this.popupMenu.insert(awtMenu, index);
}
```

**Comment by dustinkredmond** [comment]
IDE made the diff a little messy, but the changes themselves look great. Going to merge the pull request that you opened to address both of these. Do we have a test case for this specific issue? I think it may be worth adding if we don't.

**Comment by EasyG0ing1** [comment]
@dustinkredmond You just want something added to the test classes that demonstrate the bugs as being fixed? 

I can also add a test class that demonstrates how to access the TrayIcon object. There is really a good use case for that with Macs because right-clicking on the icon with a mac doesn't do the same thing as it does in Windows ... Im actually working on a class right now where I can build two different menus and have the code swap them out based on the right or left click with the mouse... could be handy to be able to offer different menu contexts ... left clicking - say for accessing points of interest within the program and right clicking for things like utility functions or app settings or just anything different than simply navigating the main parts of the app.

So I'll get cracking on some new test classes and post another PR when they're done ... but that shouldn't delay deployment since those are just examples for devs... right? ☺

**Comment by EasyG0ing1** [comment]
Added and tested the test program for this issue. Works perfectly
